#!/usr/bin/env python3

import pygame
from src.window import Window
from src.brick import brick_main
from src.class_brick import Briks
from src.file_read import read_data
from src.menu import main_menu
from src.win import win_main
from src.loose import loose_main
from src.event import all_event
from src.pause import pause_main
from sys import argv


def brick_breaker() -> (None):
    pygame.init()
    if (len(argv) == 1):
        window = read_data()
    else:
        window = read_data(argv[1])

    fnction = {0: main_menu, 1: brick_main, 2: loose_main, 3: win_main, 4: pause_main}
    while window.loop:
        fnction[window.status](window)
        window = all_event(window)
        pygame.display.flip()
        pygame.time.Clock().tick(60)
    pygame.quit()


def main() -> (None):
    if "-h" in argv:
        try:
            print(open(".config/usage", "r").read())
        except:
            print("Error: no usage found!")
        return
    brick_breaker()


if __name__ == "__main__":
    main()
